version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    reviewers:
      - "dpgraham4401"