name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# map PR labels to changelog categories
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: ':nut_and_bolt: Maintenance'
    labels:
      - 'chore'
      - 'CI/CD'
      - 'infrastructure'
      - 'documentation'

exclude-labels:
  - 'skip-changelog'

# map PR labels to semantic version updates (e.g., if  a feature is added, the minor version is incremented)
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'infrastructure'
  default: patch

# used for auto-labeling PRs, used instead of actions/labeler
# https://github.com/release-drafter/release-drafter#autolabeler
autolabeler:
  - label: 'test'
    files:
      - '**/*_test.go'
  - label: 'infrastructure'
    files:
      - 'docker-compose.yaml'
      - 'infra/**/*.tf'
    title:
      - '/terraform/i'
      - '/helm/i'
      - '/kubernetes/i'
      - '/k8/i'
  - label: 'documentation'
    files:
      - 'docs/**/*'
      - '**/README.md'
  - label: 'CI/CD'
    files:
      - '.github/**/*'
      - '**/*Dockerfile'
      - '**/*.dockerignore'
    body:
      - '/pipeline/gmi'
      - '/workflow/gmi'
  - label: 'dependencies'
    files:
      - 'go.mod'
      - 'go.sum'
  - label: 'database'
    files:
      - 'migrations/**/*.sql'

  # template for the release notes (changelog)
template: |
  ## Changes

  $CHANGES

  ## Contributor

  $CONTRIBUTORS
