version: '3.9'
services:
#  server:
#    container_name: dpg-server
#    restart: unless-stopped
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: dpgraham_v1
#      DB_USER: dg
#      DB_PASSWORD: password
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    restart: unless-stopped
    container_name: dpg-postgres
    image: 'postgres:14'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dg -d dpgraham']
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - dpg-development:/var/lib/postgresql/data

volumes:
  dpg-development:
