version: '3.9'
services:
#  server:
#    container_name: dpg-server
#    restart: unless-stopped
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    environment:
#      DPG_DB_HOST: postgres
#      DPG_DB_PORT: 5432
#      DPG_DB_NAME: dpgraham_v1
#      DPG_DB_USER: dg
#      DPG_DB_PASSWORD: password
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    restart: unless-stopped
    container_name: dpg-postgres
    image: 'postgres:14'
    environment:
      POSTGRES_DB: dpgraham
      POSTGRES_USER: dg
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dg -d dpgraham']
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - development:/var/lib/postgresql/data

volumes:
  development:
