apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
