apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dpg-server.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "dpg-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    traefik.ingress.kubernetes.io/router.middlewares: {{.Values.namespace.name}}-{{ .Values.middleware.name }}@kubernetescrd
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dpg-server.fullname" . }}
                port:
                  number: 80
