name: 'Build Docker Image'
# This custom, reusable workflow builds and pushes a Docker image to GitHub Container Registry.

on:
  workflow_call:
    inputs:
      context:
        required: false
        default: .
        type: string
        description: 'The context to use for the Docker build.'
      image_name:
        required: true
        type: string
        description: 'The name of the image to build.'
  workflow_dispatch:
    inputs:
        context:
            required: false
            default: .
            type: string
            description: 'The context to use for the Docker build.'
        image_name:
            required: true
            type: string
            description: 'The name of the image to build.'
        image_tag:
            required: true
            type: string
            description: 'The tag to use for the Docker image.'

jobs:
  build_docker_image:
    needs: test_package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.context }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dpgraham4401/${{ inputs.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
