# This Workflow deploys a Docker image to Google Cloud Run

name: Deploy to Cloud Run

on:
  push:
#  release:
#    types: [ published ]

jobs:
  build_gcp_image:
    name: Build Image for GCP
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Build Image
        uses: ./.github/workflows/build-gcp-image.yaml
        with:
          environment: production

