# This Workflow deploys a Docker image to Google Cloud Run

name: On Release

on:
  push:
#  release:
#    types: [ published ]

jobs:
  build_gcp_image:
    name: Build Image for GCP
    uses: ./.github/workflows/build-gcp-image.yaml
    with:
      environment: production
    secrets: inherit

  echo_output:
    name: Echo output
    runs-on: ubuntu-latest
    needs: build_gcp_image
    steps:
      - name: Echo output
        run: |
          echo "The image version is ${{ needs.build_gcp_image.outputs.version }}"

  deploy_to_cloud_run:
    name: Deploy to Cloud Run
    uses: ./.github/workflows/cloud-run-deploy.yaml
    needs: build_gcp_image
    with:
      environment: production
      version: ${{ needs.build_gcp_image.outputs.version }}
      service: dpgraham-api
    secrets: inherit
