# This Workflow builds and deploys a Docker image to Google Cloud Run

name: Release to Production

on:
  release:
    types:
    - published

jobs:
  build_gcp_image:
    name: Build Image for GCP
    if: github.repository == 'dpgraham-com/dpgraham-server'
    uses: ./.github/workflows/build-gcp-image.yaml
    with:
      environment: production
    secrets: inherit

  deploy_to_cloud_run:
    name: Deploy to Cloud Run
    if: github.repository == 'dpgraham-com/dpgraham-server'
    uses: ./.github/workflows/cloud-run-deploy.yaml
    needs: build_gcp_image
    with:
      environment: production
      version: ${{ needs.build_gcp_image.outputs.version }}
      service: server-prod
    secrets: inherit

  build_ghcr_image:
    name: Build Image for GHCR
    if: github.repository == 'dpgraham-com/dpgraham-server'
    uses: ./.github/workflows/build-ghcr-image.yaml
    secrets: inherit
