name: Test, Build, Push & Deploy
# This will run when a tag is pushed to main

on:
  release:
    types: [published]

env:
  IMAGE_NAME: dpg-server
  DEPLOYMENT_NAME: dpgserver-dpg-server

jobs:
  test_package:
    uses: ./.github/workflows/test.yaml

  build_docker_image:
    needs: [ test_package ]
    uses: ./.github/workflows/build-image.yaml
    with:
      context: .
      image_name: ${{ env.IMAGE_NAME }}

  deploy_docker_to_k8:
    # This deploys our newly created image to my local k8 cluster. It's temporary while we move to an off-premise solution
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image -n ${{ env.IMAGE_NAME }} deployments.apps/${{ env.DEPLOYMENT_NAME }} ${{ env.IMAGE_NAME }}=dpgraham4401/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
