name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

defaults:
  run:
    working-directory: ./infra

jobs:
  terraform_apply:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false -no-color
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_KEY }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_KEY }}

